// Generated by CoffeeScript 1.9.1
(function() {
  var PEG, coffee, grammar, parser, r;

  PEG = require('pegjs');

  grammar = 'start = a: ..';

  parser = PEG.buildParser(grammar);

  r = parser.parse('Ab');

  console.log(r);

  parser = PEG.buildParser(grammar);

  r = parser.parse("\n\t");

  console.log(r);

}).call(this);
